"""fix unique constraints on learning items

Revision ID: 2abc6ff198bf
Revises: 7868f8de3f47
Create Date: 2026-03-27 18:18:55.249658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abc6ff198bf'
down_revision: Union[str, Sequence[str], None] = '7868f8de3f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('learning_items_subject_code_key'), 'learning_items', type_='unique')
    op.drop_constraint(op.f('learning_items_title_key'), 'learning_items', type_='unique')
    op.create_unique_constraint('uq_owner_subject_code', 'learning_items', ['owner_id', 'subject_code'])
    op.create_unique_constraint('uq_owner_title', 'learning_items', ['owner_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_owner_title', 'learning_items', type_='unique')
    op.drop_constraint('uq_owner_subject_code', 'learning_items', type_='unique')
    op.create_unique_constraint(op.f('learning_items_title_key'), 'learning_items', ['title'])
    op.create_unique_constraint(op.f('learning_items_subject_code_key'), 'learning_items', ['subject_code'])
    # ### end Alembic commands ###
