"""change foreign keys to cascade delete

Revision ID: 3cddcf3a3fa3
Revises: ba79f0c458f1
Create Date: 2026-02-03 12:00:44.185892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cddcf3a3fa3'
down_revision: Union[str, Sequence[str], None] = 'ba79f0c458f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('learning_items_owner_id_fkey'), 'learning_items', type_='foreignkey')
    op.create_foreign_key(None, 'learning_items', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('learning_sessions_learning_item_id_fkey'), 'learning_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'learning_sessions', 'learning_items', ['learning_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learning_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('learning_sessions_learning_item_id_fkey'), 'learning_sessions', 'learning_items', ['learning_item_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'learning_items', type_='foreignkey')
    op.create_foreign_key(op.f('learning_items_owner_id_fkey'), 'learning_items', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
