"""Add LearningUnit table

Revision ID: 7868f8de3f47
Revises: dbc3ee0895e6
Create Date: 2026-03-21 15:30:01.894973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7868f8de3f47'
down_revision: Union[str, Sequence[str], None] = 'dbc3ee0895e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_item_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('two_marks_completed', sa.Boolean(), nullable=False),
    sa.Column('eleven_marks_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['learning_item_id'], ['learning_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_units_id'), 'learning_units', ['id'], unique=False)
    op.create_index(op.f('ix_learning_units_learning_item_id'), 'learning_units', ['learning_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_units_learning_item_id'), table_name='learning_units')
    op.drop_index(op.f('ix_learning_units_id'), table_name='learning_units')
    op.drop_table('learning_units')
    # ### end Alembic commands ###
