"""remove milestones

Revision ID: ba79f0c458f1
Revises: b767c56463f2
Create Date: 2026-02-03 07:07:08.870759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba79f0c458f1'
down_revision: Union[str, Sequence[str], None] = 'b767c56463f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_learning_item_id'), table_name='milestones')
    op.drop_table('milestones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('learning_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['learning_item_id'], ['learning_items.id'], name=op.f('milestones_learning_item_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('milestones_pkey'))
    )
    op.create_index(op.f('ix_milestones_learning_item_id'), 'milestones', ['learning_item_id'], unique=False)
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    # ### end Alembic commands ###
