"""unique constraint on title

Revision ID: c024028c21d4
Revises: ea9c333a851d
Create Date: 2026-03-15 09:24:22.248724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c024028c21d4'
down_revision: Union[str, Sequence[str], None] = 'ea9c333a851d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'learning_items', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learning_items', type_='unique')
    # ### end Alembic commands ###
