"""deleted categories column and added subjects column

Revision ID: dbc3ee0895e6
Revises: a01c1076f110
Create Date: 2026-03-15 13:34:25.856081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc3ee0895e6'
down_revision: Union[str, Sequence[str], None] = 'a01c1076f110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_items', sa.Column('subject_code', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'learning_items', ['subject_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learning_items', type_='unique')
    op.drop_column('learning_items', 'subject_code')
    # ### end Alembic commands ###
