"""add new learning categories

Revision ID: ea9c333a851d
Revises: c598a9ba14f5
Create Date: 2026-03-07 15:54:28.356139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9c333a851d'
down_revision: Union[str, Sequence[str], None] = 'c598a9ba14f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("COMMIT")
    op.execute("ALTER TYPE learningcategory ADD VALUE IF NOT EXISTS 'Acedemics'")
    op.execute("ALTER TYPE learningcategory ADD VALUE IF NOT EXISTS 'Skill_up'")
    op.execute("ALTER TYPE learningcategory ADD VALUE IF NOT EXISTS 'Responsibilities'")
    op.execute("ALTER TYPE learningcategory ADD VALUE IF NOT EXISTS 'Hobbies'")
    op.execute("ALTER TYPE learningcategory ADD VALUE IF NOT EXISTS 'Miscellaneous'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
